version: '3.0'


services:
  portfolio-fo:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: portfolio-fo:latest
    container_name: portfolio-fo
    tty: true
    labels:
      - traefik.http.routers.portfolio-fo.rule=Host(`portfolio-fo.melaine-gerard.fr`)
      - traefik.http.routers.portfolio-fo.tls=true
      - traefik.http.routers.portfolio-fo.tls.certresolver=lets-encrypt
      - "traefik.http.services.portfolio-fo.loadbalancer.server.port=3000"
      - traefik.port=80
      - "traefik.enable=true"
    networks:
      - local

networks:
  local:
    external: true